import { Routes } from '@angular/router';

const loadCitizenOnboard = () =>
  import('./citizen-onboard/citizen-onboard.component').then((m) => m.CitizenOnboardComponent);

export const ONBOARDING_ROUTES: Routes = [
  {
    path: 'citizen',
    loadComponent: loadCitizenOnboard,
  },
];

/** Legacy invite-email landing URLs generated by the backend today. */
export const ONBOARD_LEGACY_ROUTES: Routes = [
  {
    path: 'colleague/complete',
    loadComponent: loadCitizenOnboard,
  },
  {
    path: 'student/onboard-complete',
    loadComponent: loadCitizenOnboard,
  },
];
